First, import needed modules

In [89]:
import numpy as np
import pandas as pd
import os

Initalize variables

In [90]:
path = os.getcwd()
print(path)

/Users/jan/Dropbox/UP_EPQM/2222/MA/powerlinemonsters

Import datasets

In [91]:
import chardet
with open(f'{path}/data/elections/ltw/by/2018.csv', 'rb') as file:
    print(chardet.detect(file.read()))

{'encoding': 'Windows-1252', 'confidence': 0.6976500787401575, 'language': ''}

Bavaria (2008, 13, 18)

In [92]:
by08 = pd.read_csv(f'{path}/data/elections/ltw/by/2008.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
by13 = pd.read_csv(f'{path}/data/elections/ltw/by/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
by18 = pd.read_csv(f'{path}/data/elections/ltw/by/2018.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [93]:
by18.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,14.10.18,9,Bayern,9479428.0,"72,3",6782374.0,2523041.0,654539.0,1196178.0,345250.0,218944.0,694311.0,1150112.0
1,14.10.18,91,"Oberbayern, Regierungsbezirk",3203709.0,"74,6",2367136.0,798011.0,221710.0,527462.0,151403.0,74839.0,202708.0,391004.0
2,14.10.18,9161,Ingolstadt,90643.0,64,57337.0,20784.0,5217.0,9517.0,3972.0,2894.0,7383.0,7572.0
3,14.10.18,9162,"München, Landeshauptstadt",910459.0,"72,7",656649.0,162579.0,84340.0,204303.0,57488.0,30752.0,42441.0,74748.0
4,14.10.18,9163,Rosenheim,41029.0,"68,2",27618.0,9396.0,2254.0,5767.0,1620.0,967.0,3203.0,4412.0

Hesse (2009, 13, 18)

In [94]:
he09 = pd.read_csv(f'{path}/data/elections/ltw/he/2009.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
he13 = pd.read_csv(f'{path}/data/elections/ltw/he/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
he18 = pd.read_csv(f'{path}/data/elections/ltw/he/2018.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [95]:
he09.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,18.01.09,6,Hessen,4375286.0,61,2591872.0,963763.0,614648.0,356040.0,420426.0,139074.0,NaN,97921.0
1,18.01.09,64,"Darmstadt, Regierungsbezirk",2620658.0,"61,9",1576303.0,593959.0,327432.0,240227.0,270740.0,85101.0,NaN,58844.0
2,18.01.09,6411,"Darmstadt, kreisfreie Stadt",98087.0,"62,8",60073.0,17269.0,12730.0,14907.0,9051.0,4322.0,NaN,1794.0
3,18.01.09,6412,"Frankfurt am Main, kreisfreie Stadt",395834.0,"59,4",229893.0,75211.0,45421.0,45134.0,38640.0,18003.0,NaN,7484.0
4,18.01.09,6413,"Offenbach am Main, kreisfreie Stadt",66517.0,"53,6",34483.0,11694.0,7311.0,6350.0,4881.0,2598.0,NaN,1649.0

NRW (2010, 12, 17)

In [96]:
nrw10 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2010.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
nrw12 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2012.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
nrw17 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2017.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [97]:
nrw10.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,09.05.10,5,Nordrhein-Westfalen,13267052.0,"59,3",7760546.0,2681700.0,2675818.0,941162.0,522229.0,435627.0,NaN,504010.0
1,09.05.10,51,"Düsseldorf, Regierungsbezirk",3803015.0,"58,9",2212669.0,742241.0,767674.0,262033.0,157156.0,130781.0,NaN,152784.0
2,09.05.10,5111,"Düsseldorf, kreisfreie Stadt",412910.0,"61,1",249688.0,87499.0,72533.0,37996.0,21710.0,14934.0,NaN,15016.0
3,09.05.10,5112,"Duisburg, kreisfreie Stadt",344154.0,"54,2",184005.0,44331.0,82532.0,17521.0,7242.0,14657.0,NaN,17722.0
4,09.05.10,5113,"Essen, kreisfreie Stadt",433631.0,"58,8",251546.0,72507.0,101932.0,30175.0,13547.0,16265.0,NaN,17120.0

Lower Saxony (2008, 13, 17)

In [98]:
ns08 = pd.read_csv(f'{path}/data/elections/ltw/ns/2008.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
ns13 = pd.read_csv(f'{path}/data/elections/ltw/ns/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
ns17 = pd.read_csv(f'{path}/data/elections/ltw/ns/2017.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [99]:
ns08.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,27.01.08,3,Niedersachsen,6087297.0,"57,1",3425426.0,1456742.0,1036727.0,274221.0,279826.0,243361.0,NaN,134549.0
1,27.01.08,31,"Braunschweig, Stat. Region",1263011.0,"57,2",710602.0,276493.0,241568.0,54767.0,53255.0,56762.0,NaN,27757.0
2,27.01.08,3101,"Braunschweig, kreisfreie Stadt",187773.0,"57,2",106089.0,39106.0,33148.0,11695.0,8580.0,10131.0,NaN,3429.0
3,27.01.08,3102,"Salzgitter, kreisfreie Stadt",78313.0,"54,5",41776.0,15656.0,16405.0,1793.0,2398.0,3688.0,NaN,1836.0
4,27.01.08,3103,"Wolfsburg, kreisfreie Stadt",90631.0,"51,6",45996.0,19834.0,14496.0,2994.0,3078.0,3617.0,NaN,1977.0

Thuringia (2009, 14, 19)

In [100]:
th09 = pd.read_csv(f'{path}/data/elections/ltw/th/2009.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
th14 = pd.read_csv(f'{path}/data/elections/ltw/th/2014.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
th19 = pd.read_csv(f'{path}/data/elections/ltw/th/2019.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [101]:
th09.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,30.08.09,16,Thüringen,1910074.0,"56,2",1054297.0,329302.0,195363.0,64912.0,80600.0,288915.0,NaN,95205.0
1,30.08.09,16051,"Erfurt, kreisfreie Stadt",167444.0,"58,1",95498.0,24134.0,18875.0,10041.0,7226.0,27096.0,NaN,8126.0
2,30.08.09,16052,"Gera, kreisfreie Stadt",85482.0,53,44488.0,12197.0,7002.0,2486.0,3727.0,16096.0,NaN,2980.0
3,30.08.09,16053,"Jena, kreisfreie Stadt",84679.0,"59,1",49407.0,11155.0,11001.0,6818.0,4571.0,12840.0,NaN,3022.0
4,30.08.09,16054,"Suhl, kreisfreie Stadt",34101.0,55,18489.0,4590.0,2949.0,1091.0,1287.0,7108.0,NaN,1464.0

Add year column and state number to dataframes

In [102]:
dfs = [by08, by13, by18, he09, he13, he18, nrw10, nrw12, nrw17, ns08, ns13, ns17, th09, th14, th19]
years = [2008, 2013, 2018, 2009, 2013, 2018, 2010, 2012, 2017, 2008, 2013, 2017, 2009, 2014, 2019]
states = ['Bavaria', 'Bavaria', 'Bavaria', 'Hesse', 'Hesse', 'Hesse', 'NRW', 'NRW', 'NRW', 'Lower-Saxony', 'Lower-Saxony', 'Lower-Saxony',  'Thuringia', 'Thuringia', 'Thuringia']
for df, year, state in zip(dfs, years, states):
    df.insert(loc=0, column='year', value=year)
    df.insert(loc=0, column='Land', value=state)

Concatenate dataframes

In [103]:
dfs = [by08, by13, by18, he09, he13, he18, nrw10, nrw12, nrw17, ns08, ns13, ns17, th09, th14, th19]
ltw = pd.concat(dfs, sort=False)

Fix the AGS

In [104]:
ltw['AGS'] = np.where(ltw['AGS'].str.len() < 6, ltw['AGS'] + '000', ltw['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4 - 5 digits before, 7 -8 after)
ltw['AGS'] = np.where(ltw['AGS'].str.len() < 8, '0' + ltw['AGS'], ltw['AGS']) # add leading 0 for state ids < 10

Drop everything that is not a Gemeinde (e.g. data for States)

In [105]:
#ltw['AGS_len'] = ltw['AGS'].str.len()
ltw = ltw[ltw['AGS'].str.len() == 8]

Still there are some duplicates, e.g. Gießen Stadt and Landkreis --> these won't be matched when merging with treatment data

In [106]:
ltw.head()

,Land,year,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
2,Bavaria,2008,28.09.08,09161000,Ingolstadt,87814.0,"49,1",42062.0,16784.0,8303.0,3537.0,3429.0,2265.0,NaN,7745.0
3,Bavaria,2008,28.09.08,09162000,"München, Landeshauptstadt",882602.0,57,496289.0,157505.0,139864.0,71528.0,62369.0,25746.0,NaN,39279.0
4,Bavaria,2008,28.09.08,09163000,Rosenheim,40902.0,"52,1",20831.0,8481.0,3788.0,2686.0,1739.0,938.0,NaN,3200.0
5,Bavaria,2008,28.09.08,09171000,"Altötting, Landkreis",82425.0,"56,4",45350.0,21106.0,8030.0,3542.0,3411.0,1531.0,NaN,7731.0
6,Bavaria,2008,28.09.08,09171111,"Altötting, St",9731.0,"52,1",4911.0,2273.0,567.0,335.0,324.0,191.0,NaN,1223.0

Clean data and sum votes for AfD and Andere

In [107]:
ltw.rename(columns = {'GŸltige Stimmen':'Gültig', 'GrŸne': 'Grüne'}, inplace = True)
andere = ['AfD', 'Sonstige Parteien']
ltw['Andere'] = ltw[andere].sum(axis=1)

ltw.head()

,Land,year,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,Gültig,Union,SPD,Grüne,FDP,Linke,AfD,Sonstige Parteien,Andere
2,Bavaria,2008,28.09.08,09161000,Ingolstadt,87814.0,"49,1",42062.0,16784.0,8303.0,3537.0,3429.0,2265.0,NaN,7745.0,7745.0
3,Bavaria,2008,28.09.08,09162000,"München, Landeshauptstadt",882602.0,57,496289.0,157505.0,139864.0,71528.0,62369.0,25746.0,NaN,39279.0,39279.0
4,Bavaria,2008,28.09.08,09163000,Rosenheim,40902.0,"52,1",20831.0,8481.0,3788.0,2686.0,1739.0,938.0,NaN,3200.0,3200.0
5,Bavaria,2008,28.09.08,09171000,"Altötting, Landkreis",82425.0,"56,4",45350.0,21106.0,8030.0,3542.0,3411.0,1531.0,NaN,7731.0,7731.0
6,Bavaria,2008,28.09.08,09171111,"Altötting, St",9731.0,"52,1",4911.0,2273.0,567.0,335.0,324.0,191.0,NaN,1223.0,1223.0

Calculate vote shares in percent

In [108]:
parties = ['Union',	'SPD', 'FDP', 'Linke', 'Grüne', 'Andere']
for party in parties:
    ltw.loc[:, party] = (ltw[party] / ltw['Gültig'])*100
ltw.head(10)

,Land,year,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,Gültig,Union,SPD,Grüne,FDP,Linke,AfD,Sonstige Parteien,Andere
2,Bavaria,2008,28.09.08,09161000,Ingolstadt,87814.0,"49,1",42062.0,39.903000,19.739908,8.409015,8.152251,5.384908,NaN,7745.0,18.413295
3,Bavaria,2008,28.09.08,09162000,"München, Landeshauptstadt",882602.0,57,496289.0,31.736549,28.181967,14.412570,12.567073,5.187703,NaN,39279.0,7.914542
4,Bavaria,2008,28.09.08,09163000,Rosenheim,40902.0,"52,1",20831.0,40.713360,18.184437,12.894244,8.348135,4.502904,NaN,3200.0,15.361721
5,Bavaria,2008,28.09.08,09171000,"Altötting, Landkreis",82425.0,"56,4",45350.0,46.540243,17.706725,7.810364,7.521499,3.375965,NaN,7731.0,17.047409
6,Bavaria,2008,28.09.08,09171111,"Altötting, St",9731.0,"52,1",4911.0,46.283853,11.545510,6.821421,6.597434,3.889228,NaN,1223.0,24.903278
7,Bavaria,2008,28.09.08,09171112,"Burghausen, St",13273.0,"56,6",7326.0,40.281190,26.003276,9.555010,10.455910,3.931204,NaN,718.0,9.800710
8,Bavaria,2008,28.09.08,09171113,Burgkirchen a.d.Alz,7664.0,"51,3",3846.0,48.465939,19.344774,6.838274,7.124285,2.704108,NaN,597.0,15.522621
9,Bavaria,2008,28.09.08,09171114,Emmerting,3081.0,"57,5",1722.0,42.508711,16.202091,7.897793,9.407666,2.613240,NaN,369.0,21.428571
10,Bavaria,2008,28.09.08,09171115,Erlbach,950.0,"63,7",592.0,59.290541,6.418919,5.574324,7.263514,2.027027,NaN,116.0,19.594595
11,Bavaria,2008,28.09.08,09171116,Feichten a.d.Alz,890.0,"61,1",536.0,52.611940,9.328358,13.432836,7.649254,4.104478,NaN,71.0,13.246269

Add post-treatment indicator

In [109]:
ltw['post_2014'] = np.where(ltw['year'] >= 2014, 1, 0)
ltw['post_2010'] = np.where(ltw['year'] > 2010, 1, 0)
ltw = ltw.sort_values(['AGS', 'year'])
ltw.head(10)

,Land,year,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,Gültig,Union,SPD,Grüne,FDP,Linke,AfD,Sonstige Parteien,Andere,post_2014,post_2010
2,Lower-Saxony,2008,27.01.08,03101000,"Braunschweig, kreisfreie Stadt",187773.0,"57,2",106089.0,36.861503,31.245464,11.023763,8.087549,9.549529,NaN,3429.0,3.232192,0,0
2,Lower-Saxony,2013,20.01.13,03101000,"Braunschweig, kreisfreie Stadt",192582.0,"59,9",114222.0,29.666789,33.671272,18.608499,8.250600,4.246117,NaN,6347.0,5.556723,0,1
2,Lower-Saxony,2017,15.10.17,03101000,"Braunschweig, kreisfreie Stadt",190754.0,"63,7",120937.0,26.342641,37.604703,11.862375,7.904115,6.741527,7303.0,4240.0,9.544639,1,1
3,Lower-Saxony,2008,27.01.08,03102000,"Salzgitter, kreisfreie Stadt",78313.0,"54,5",41776.0,37.476063,39.268958,4.291938,5.740138,8.828035,NaN,1836.0,4.394868,0,0
3,Lower-Saxony,2013,20.01.13,03102000,"Salzgitter, kreisfreie Stadt",75483.0,"52,5",38983.0,30.880127,44.075623,9.252751,6.053921,4.135136,NaN,2184.0,5.602442,0,1
3,Lower-Saxony,2017,15.10.17,03102000,"Salzgitter, kreisfreie Stadt",73602.0,"56,9",41561.0,24.445995,45.203436,4.266019,5.319891,4.862732,5665.0,944.0,15.901927,1,1
4,Lower-Saxony,2008,27.01.08,03103000,"Wolfsburg, kreisfreie Stadt",90631.0,"51,6",45996.0,43.121141,31.515784,6.509262,6.691886,7.863727,NaN,1977.0,4.298200,0,0
4,Lower-Saxony,2013,20.01.13,03103000,"Wolfsburg, kreisfreie Stadt",92716.0,"53,1",48597.0,37.629895,35.812910,10.901908,7.342017,3.210075,NaN,2480.0,5.103196,0,1
4,Lower-Saxony,2017,15.10.17,03103000,"Wolfsburg, kreisfreie Stadt",89468.0,"58,2",51820.0,29.942107,43.211115,5.754535,6.092242,4.525280,4177.0,1251.0,10.474720,1,1
5,Lower-Saxony,2008,27.01.08,03151000,"Gifhorn, Landkreis",132690.0,57,74634.0,45.717769,30.467347,6.253182,6.957955,6.738216,NaN,2885.0,3.865530,0,0

Export dataset

In [110]:
ltw = ltw[['AGS', 'Land', 'year', 'post_2010', 'post_2014', 'Union', 'SPD', 'Grüne', 'FDP', 'Linke', 'Andere']]
ltw = ltw.set_index(['AGS', 'year'])
ltw.to_csv(f'{path}/data/ltw.csv', encoding = 'utf-8-sig')
ltw.head()

                       Land  post_2010  post_2014      Union        SPD  \
AGS      year
03101000 2008  Lower-Saxony          0          0  36.861503  31.245464
         2013  Lower-Saxony          1          0  29.666789  33.671272
         2017  Lower-Saxony          1          1  26.342641  37.604703
03102000 2008  Lower-Saxony          0          0  37.476063  39.268958
         2013  Lower-Saxony          1          0  30.880127  44.075623

                   Grüne       FDP     Linke    Andere
AGS      year
03101000 2008  11.023763  8.087549  9.549529  3.232192
         2013  18.608499  8.250600  4.246117  5.556723
         2017  11.862375  7.904115  6.741527  9.544639
03102000 2008   4.291938  5.740138  8.828035  4.394868
         2013   9.252751  6.053921  4.135136  5.602442

In [111]:
ltw = pd.read_csv(f'{path}/data/ltw.csv', converters={'AGS': str, 'Land': str})
ltw.head()

,AGS,year,Land,post_2010,post_2014,Union,SPD,Grüne,FDP,Linke,Andere
0,03101000,2008,Lower-Saxony,0,0,36.861503,31.245464,11.023763,8.087549,9.549529,3.232192
1,03101000,2013,Lower-Saxony,1,0,29.666789,33.671272,18.608499,8.250600,4.246117,5.556723
2,03101000,2017,Lower-Saxony,1,1,26.342641,37.604703,11.862375,7.904115,6.741527,9.544639
3,03102000,2008,Lower-Saxony,0,0,37.476063,39.268958,4.291938,5.740138,8.828035,4.394868
4,03102000,2013,Lower-Saxony,1,0,30.880127,44.075623,9.252751,6.053921,4.135136,5.602442

Merge with treatment dataset

In [112]:
treatment = pd.read_csv(f'{path}/data/treatment.csv', converters = {'AGS': str})
#data = btw.join(treatment.set_index(['AGS']))
data = pd.merge(ltw, treatment, on='AGS', how='outer', indicator=True)
data.head(10)

,AGS,year,Land,post_2010,post_2014,Union,SPD,Grüne,FDP,Linke,Andere,GEN,treated_0,treated_10,treated_20,treated_30,treated_50,treated_100,_merge
0,03101000,2008.0,Lower-Saxony,0.0,0.0,36.861503,31.245464,11.023763,8.087549,9.549529,3.232192,Braunschweig,0.0,0.0,0.0,0.0,0.0,1.0,both
1,03101000,2013.0,Lower-Saxony,1.0,0.0,29.666789,33.671272,18.608499,8.250600,4.246117,5.556723,Braunschweig,0.0,0.0,0.0,0.0,0.0,1.0,both
2,03101000,2017.0,Lower-Saxony,1.0,1.0,26.342641,37.604703,11.862375,7.904115,6.741527,9.544639,Braunschweig,0.0,0.0,0.0,0.0,0.0,1.0,both
3,03102000,2008.0,Lower-Saxony,0.0,0.0,37.476063,39.268958,4.291938,5.740138,8.828035,4.394868,Salzgitter,0.0,0.0,0.0,0.0,0.0,1.0,both
4,03102000,2013.0,Lower-Saxony,1.0,0.0,30.880127,44.075623,9.252751,6.053921,4.135136,5.602442,Salzgitter,0.0,0.0,0.0,0.0,0.0,1.0,both
5,03102000,2017.0,Lower-Saxony,1.0,1.0,24.445995,45.203436,4.266019,5.319891,4.862732,15.901927,Salzgitter,0.0,0.0,0.0,0.0,0.0,1.0,both
6,03103000,2008.0,Lower-Saxony,0.0,0.0,43.121141,31.515784,6.509262,6.691886,7.863727,4.298200,Wolfsburg,0.0,0.0,0.0,0.0,0.0,0.0,both
7,03103000,2013.0,Lower-Saxony,1.0,0.0,37.629895,35.812910,10.901908,7.342017,3.210075,5.103196,Wolfsburg,0.0,0.0,0.0,0.0,0.0,0.0,both
8,03103000,2017.0,Lower-Saxony,1.0,1.0,29.942107,43.211115,5.754535,6.092242,4.525280,10.474720,Wolfsburg,0.0,0.0,0.0,0.0,0.0,0.0,both
9,03151000,2008.0,Lower-Saxony,0.0,0.0,45.717769,30.467347,6.253182,6.957955,6.738216,3.865530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

Inspect merge results

In [113]:
print(data['_merge'].describe())

count     22680
unique        3
top        both
freq      14181
Name: _merge, dtype: object

Clean data

In [114]:
data = data[data['_merge'] == 'both']
data = data.set_index(['AGS', 'GEN', 'year'])
data = data.drop(columns=['_merge'])
data.head(10)

                                      Land  post_2010  post_2014      Union  \
AGS      GEN          year
03101000 Braunschweig 2008.0  Lower-Saxony        0.0        0.0  36.861503
                      2013.0  Lower-Saxony        1.0        0.0  29.666789
                      2017.0  Lower-Saxony        1.0        1.0  26.342641
03102000 Salzgitter   2008.0  Lower-Saxony        0.0        0.0  37.476063
                      2013.0  Lower-Saxony        1.0        0.0  30.880127
                      2017.0  Lower-Saxony        1.0        1.0  24.445995
03103000 Wolfsburg    2008.0  Lower-Saxony        0.0        0.0  43.121141
                      2013.0  Lower-Saxony        1.0        0.0  37.629895
                      2017.0  Lower-Saxony        1.0        1.0  29.942107
03151001 Adenbüttel   2008.0  Lower-Saxony        0.0        0.0  47.568209

                                    SPD      Grüne       FDP     Linke  \
AGS      GEN          year
03101000 Braunschweig 2008.0  31.245464  11.023763  8.087549  9.549529
                      2013.0  33.671272  18.608499  8.250600  4.246117
                      2017.0  37.604703  11.862375  7.904115  6.741527
03102000 Salzgitter   2008.0  39.268958   4.291938  5.740138  8.828035
                      2013.0  44.075623   9.252751  6.053921  4.135136
                      2017.0  45.203436   4.266019  5.319891  4.862732
03103000 Wolfsburg    2008.0  31.515784   6.509262  6.691886  7.863727
                      2013.0  35.812910  10.901908  7.342017  3.210075
                      2017.0  43.211115   5.754535  6.092242  4.525280
03151001 Adenbüttel   2008.0  30.960854   6.287070  7.117438  4.863582

                                 Andere  treated_0  treated_10  treated_20  \
AGS      GEN          year
03101000 Braunschweig 2008.0   3.232192        0.0         0.0         0.0
                      2013.0   5.556723        0.0         0.0         0.0
                      2017.0   9.544639        0.0         0.0         0.0
03102000 Salzgitter   2008.0   4.394868        0.0         0.0         0.0
                      2013.0   5.602442        0.0         0.0         0.0
                      2017.0  15.901927        0.0         0.0         0.0
03103000 Wolfsburg    2008.0   4.298200        0.0         0.0         0.0
                      2013.0   5.103196        0.0         0.0         0.0
                      2017.0  10.474720        0.0         0.0         0.0
03151001 Adenbüttel   2008.0   3.202847        0.0         0.0         0.0

                              treated_30  treated_50  treated_100
AGS      GEN          year
03101000 Braunschweig 2008.0         0.0         0.0          1.0
                      2013.0         0.0         0.0          1.0
                      2017.0         0.0         0.0          1.0
03102000 Salzgitter   2008.0         0.0         0.0          1.0
                      2013.0         0.0         0.0          1.0
                      2017.0         0.0         0.0          1.0
03103000 Wolfsburg    2008.0         0.0         0.0          0.0
                      2013.0         0.0         0.0          0.0
                      2017.0         0.0         0.0          0.0
03151001 Adenbüttel   2008.0         0.0         0.0          1.0

Drop missing values

In [115]:
data = data.dropna(axis='rows', how='any', subset=['Union',	'SPD', 'FDP', 'Linke', 'Grüne', 'Andere'])

Export dataset

In [116]:
data.to_csv(f'{path}/data/ltw_treatment.csv', encoding = 'utf-8-sig')