First, import needed modules

In [1]:
import numpy as np
import pandas as pd
import os

Initalize variables

In [2]:
path = os.getcwd()
print(path)

/Users/jan/Dropbox/UP_EPQM/2222/MA/powerlinemonsters

Import dataset

In [9]:
ltw = pd.read_csv(f'{path}/data/ltw.csv', converters={'AGS': str, 'Land': str})
ltw.head()

,AGS,year,Land,post_2014,Union,SPD,Grüne,FDP,Linke,Andere
0,03101000,2008,03,0,36.861503,31.245464,11.023763,8.087549,9.549529,3.232192
1,03101000,2013,03,0,29.666789,33.671272,18.608499,8.250600,4.246117,5.556723
2,03101000,2017,03,1,26.342641,37.604703,11.862375,7.904115,6.741527,9.544639
3,03102000,2008,03,0,37.476063,39.268958,4.291938,5.740138,8.828035,4.394868
4,03102000,2013,03,0,30.880127,44.075623,9.252751,6.053921,4.135136,5.602442

Merge with treatment dataset

In [10]:
treatment = pd.read_csv(f'{path}/data/treatment.csv', converters = {'AGS': str})
#data = btw.join(treatment.set_index(['AGS']))
data = pd.merge(ltw, treatment, on='AGS', how='outer', indicator=True)
data.head(10)

,AGS,year,Land,post_2014,Union,SPD,Grüne,FDP,Linke,Andere,GEN,treated_0,treated_10,treated_20,treated_30,treated_50,treated_100,_merge
0,03101000,2008.0,03,0.0,36.861503,31.245464,11.023763,8.087549,9.549529,3.232192,Braunschweig,0.0,0.0,0.0,0.0,0.0,1.0,both
1,03101000,2013.0,03,0.0,29.666789,33.671272,18.608499,8.250600,4.246117,5.556723,Braunschweig,0.0,0.0,0.0,0.0,0.0,1.0,both
2,03101000,2017.0,03,1.0,26.342641,37.604703,11.862375,7.904115,6.741527,9.544639,Braunschweig,0.0,0.0,0.0,0.0,0.0,1.0,both
3,03102000,2008.0,03,0.0,37.476063,39.268958,4.291938,5.740138,8.828035,4.394868,Salzgitter,0.0,0.0,0.0,0.0,0.0,1.0,both
4,03102000,2013.0,03,0.0,30.880127,44.075623,9.252751,6.053921,4.135136,5.602442,Salzgitter,0.0,0.0,0.0,0.0,0.0,1.0,both
5,03102000,2017.0,03,1.0,24.445995,45.203436,4.266019,5.319891,4.862732,15.901927,Salzgitter,0.0,0.0,0.0,0.0,0.0,1.0,both
6,03103000,2008.0,03,0.0,43.121141,31.515784,6.509262,6.691886,7.863727,4.298200,Wolfsburg,0.0,0.0,0.0,0.0,0.0,0.0,both
7,03103000,2013.0,03,0.0,37.629895,35.812910,10.901908,7.342017,3.210075,5.103196,Wolfsburg,0.0,0.0,0.0,0.0,0.0,0.0,both
8,03103000,2017.0,03,1.0,29.942107,43.211115,5.754535,6.092242,4.525280,10.474720,Wolfsburg,0.0,0.0,0.0,0.0,0.0,0.0,both
9,03151000,2008.0,03,0.0,45.717769,30.467347,6.253182,6.957955,6.738216,3.865530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

Inspect merge results

In [11]:
print(data['_merge'].describe())

count     22680
unique        3
top        both
freq      14181
Name: _merge, dtype: object

Clean data

In [12]:
data = data[data['_merge'] == 'both']
data = data.set_index(['AGS', 'GEN', 'year'])
data = data.drop(columns=['_merge'])
data.head(10)

                             Land  post_2014      Union        SPD      Grüne  \
AGS      GEN          year
03101000 Braunschweig 2008.0   03        0.0  36.861503  31.245464  11.023763
                      2013.0   03        0.0  29.666789  33.671272  18.608499
                      2017.0   03        1.0  26.342641  37.604703  11.862375
03102000 Salzgitter   2008.0   03        0.0  37.476063  39.268958   4.291938
                      2013.0   03        0.0  30.880127  44.075623   9.252751
                      2017.0   03        1.0  24.445995  45.203436   4.266019
03103000 Wolfsburg    2008.0   03        0.0  43.121141  31.515784   6.509262
                      2013.0   03        0.0  37.629895  35.812910  10.901908
                      2017.0   03        1.0  29.942107  43.211115   5.754535
03151001 Adenbüttel   2008.0   03        0.0  47.568209  30.960854   6.287070

                                   FDP     Linke     Andere  treated_0  \
AGS      GEN          year
03101000 Braunschweig 2008.0  8.087549  9.549529   3.232192        0.0
                      2013.0  8.250600  4.246117   5.556723        0.0
                      2017.0  7.904115  6.741527   9.544639        0.0
03102000 Salzgitter   2008.0  5.740138  8.828035   4.394868        0.0
                      2013.0  6.053921  4.135136   5.602442        0.0
                      2017.0  5.319891  4.862732  15.901927        0.0
03103000 Wolfsburg    2008.0  6.691886  7.863727   4.298200        0.0
                      2013.0  7.342017  3.210075   5.103196        0.0
                      2017.0  6.092242  4.525280  10.474720        0.0
03151001 Adenbüttel   2008.0  7.117438  4.863582   3.202847        0.0

                              treated_10  treated_20  treated_30  treated_50  \
AGS      GEN          year
03101000 Braunschweig 2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03102000 Salzgitter   2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03103000 Wolfsburg    2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03151001 Adenbüttel   2008.0         0.0         0.0         0.0         0.0

                              treated_100
AGS      GEN          year
03101000 Braunschweig 2008.0          1.0
                      2013.0          1.0
                      2017.0          1.0
03102000 Salzgitter   2008.0          1.0
                      2013.0          1.0
                      2017.0          1.0
03103000 Wolfsburg    2008.0          0.0
                      2013.0          0.0
                      2017.0          0.0
03151001 Adenbüttel   2008.0          1.0

Interact treatment dummies with post-treatment indicator

In [13]:
dummies = ['treated_0', 'treated_10', 'treated_20', 'treated_30', 'treated_50', 'treated_100']
for dummy in dummies:
    data.insert(loc=len(data.columns), column=f'{dummy}*post_2014', value=(data[dummy]*data['post_2014']))
data.head(20)

                             Land  post_2014      Union        SPD      Grüne  \
AGS      GEN          year
03101000 Braunschweig 2008.0   03        0.0  36.861503  31.245464  11.023763
                      2013.0   03        0.0  29.666789  33.671272  18.608499
                      2017.0   03        1.0  26.342641  37.604703  11.862375
03102000 Salzgitter   2008.0   03        0.0  37.476063  39.268958   4.291938
                      2013.0   03        0.0  30.880127  44.075623   9.252751
                      2017.0   03        1.0  24.445995  45.203436   4.266019
03103000 Wolfsburg    2008.0   03        0.0  43.121141  31.515784   6.509262
                      2013.0   03        0.0  37.629895  35.812910  10.901908
                      2017.0   03        1.0  29.942107  43.211115   5.754535
03151001 Adenbüttel   2008.0   03        0.0  47.568209  30.960854   6.287070
                      2013.0   03        0.0  37.806177  35.995740  13.738019
                      2017.0   03        1.0  34.125270  40.604752   8.099352
03151002 Barwedel     2008.0   03        0.0  46.491228  28.728070   7.236842
                      2013.0   03        0.0  36.575053  35.095137  14.799154
                      2017.0   03        1.0  31.808279  40.958606   7.407407
03151003 Bergfeld     2008.0   03        0.0  52.466368  27.130045   5.605381
                      2013.0   03        0.0  50.352941  29.647059   9.176471
                      2017.0   03        1.0  40.338164  42.270531   3.381643
03151004 Bokensdorf   2008.0   03        0.0  36.784741  35.694823   5.449591
                      2013.0   03        0.0  32.879819  39.909297  14.285714

                                   FDP      Linke     Andere  treated_0  \
AGS      GEN          year
03101000 Braunschweig 2008.0  8.087549   9.549529   3.232192        0.0
                      2013.0  8.250600   4.246117   5.556723        0.0
                      2017.0  7.904115   6.741527   9.544639        0.0
03102000 Salzgitter   2008.0  5.740138   8.828035   4.394868        0.0
                      2013.0  6.053921   4.135136   5.602442        0.0
                      2017.0  5.319891   4.862732  15.901927        0.0
03103000 Wolfsburg    2008.0  6.691886   7.863727   4.298200        0.0
                      2013.0  7.342017   3.210075   5.103196        0.0
                      2017.0  6.092242   4.525280  10.474720        0.0
03151001 Adenbüttel   2008.0  7.117438   4.863582   3.202847        0.0
                      2013.0  6.602769   1.916933   3.940362        0.0
                      2017.0  5.615551   2.915767   8.639309        0.0
03151002 Barwedel     2008.0  6.359649   7.675439   3.508772        0.0
                      2013.0  6.765328   2.325581   4.439746        0.0
                      2017.0  6.535948   4.139434   9.150327        0.0
03151003 Bergfeld     2008.0  5.381166   5.156951   4.260090        0.0
                      2013.0  6.352941   1.882353   2.588235        0.0
                      2017.0  4.589372   2.898551   6.521739        0.0
03151004 Bokensdorf   2008.0  5.722071  10.354223   5.994550        0.0
                      2013.0  5.442177   1.814059   5.668934        0.0

                              treated_10  treated_20  treated_30  treated_50  \
AGS      GEN          year
03101000 Braunschweig 2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03102000 Salzgitter   2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03103000 Wolfsburg    2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03151001 Adenbüttel   2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03151002 Barwedel     2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03151003 Bergfeld     2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0
                      2017.0         0.0         0.0         0.0         0.0
03151004 Bokensdorf   2008.0         0.0         0.0         0.0         0.0
                      2013.0         0.0         0.0         0.0         0.0

                              treated_100  treated_0*post_2014  \
AGS      GEN          year
03101000 Braunschweig 2008.0          1.0                  0.0
                      2013.0          1.0                  0.0
                      2017.0          1.0                  0.0
03102000 Salzgitter   2008.0          1.0                  0.0
                      2013.0          1.0                  0.0
                      2017.0          1.0                  0.0
03103000 Wolfsburg    2008.0          0.0                  0.0
                      2013.0          0.0                  0.0
                      2017.0          0.0                  0.0
03151001 Adenbüttel   2008.0          1.0                  0.0
                      2013.0          1.0                  0.0
                      2017.0          1.0                  0.0
03151002 Barwedel     2008.0          0.0                  0.0
                      2013.0          0.0                  0.0
                      2017.0          0.0                  0.0
03151003 Bergfeld     2008.0          0.0                  0.0
                      2013.0          0.0                  0.0
                      2017.0          0.0                  0.0
03151004 Bokensdorf   2008.0          0.0                  0.0
                      2013.0          0.0                  0.0

                              treated_10*post_2014  treated_20*post_2014  \
AGS      GEN          year
03101000 Braunschweig 2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03102000 Salzgitter   2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03103000 Wolfsburg    2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03151001 Adenbüttel   2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03151002 Barwedel     2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03151003 Bergfeld     2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03151004 Bokensdorf   2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0

                              treated_30*post_2014  treated_50*post_2014  \
AGS      GEN          year
03101000 Braunschweig 2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03102000 Salzgitter   2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03103000 Wolfsburg    2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03151001 Adenbüttel   2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03151002 Barwedel     2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03151003 Bergfeld     2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0
                      2017.0                   0.0                   0.0
03151004 Bokensdorf   2008.0                   0.0                   0.0
                      2013.0                   0.0                   0.0

                              treated_100*post_2014
AGS      GEN          year
03101000 Braunschweig 2008.0                    0.0
                      2013.0                    0.0
                      2017.0                    1.0
03102000 Salzgitter   2008.0                    0.0
                      2013.0                    0.0
                      2017.0                    1.0
03103000 Wolfsburg    2008.0                    0.0
                      2013.0                    0.0
                      2017.0                    0.0
03151001 Adenbüttel   2008.0                    0.0
                      2013.0                    0.0
                      2017.0                    1.0
03151002 Barwedel     2008.0                    0.0
                      2013.0                    0.0
                      2017.0                    0.0
03151003 Bergfeld     2008.0                    0.0
                      2013.0                    0.0
                      2017.0                    0.0
03151004 Bokensdorf   2008.0                    0.0
                      2013.0                    0.0

Drop missing values

In [14]:
data = data.dropna(axis='rows', how='any', subset=['Union',	'SPD', 'FDP', 'Linke', 'Grüne', 'Andere'])

Export dataset

In [15]:
data.to_csv(f'{path}/data/ltw_treatment.csv', encoding = 'utf-8-sig')