First, import needed modules

In [483]:
import numpy as np
import pandas as pd
import os

Initalize variables

In [484]:
path = os.getcwd()
print(path)

/Users/jan/Dropbox/UP_EPQM/2222/MA/powerlinemonsters

Import datasets

Bavaria (2008, 13, 18)

In [485]:
by08 = pd.read_csv(f'{path}/data/elections/ltw/by/2008.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
by13 = pd.read_csv(f'{path}/data/elections/ltw/by/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
by18 = pd.read_csv(f'{path}/data/elections/ltw/by/2018.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [486]:
by18.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,14.10.18,9,Bayern,9479428.0,"72,3",6782374.0,2523041.0,654539.0,1196178.0,345250.0,218944.0,694311.0,1150112.0
1,14.10.18,91,"Oberbayern, Regierungsbezirk",3203709.0,"74,6",2367136.0,798011.0,221710.0,527462.0,151403.0,74839.0,202708.0,391004.0
2,14.10.18,9161,Ingolstadt,90643.0,64,57337.0,20784.0,5217.0,9517.0,3972.0,2894.0,7383.0,7572.0
3,14.10.18,9162,"München, Landeshauptstadt",910459.0,"72,7",656649.0,162579.0,84340.0,204303.0,57488.0,30752.0,42441.0,74748.0
4,14.10.18,9163,Rosenheim,41029.0,"68,2",27618.0,9396.0,2254.0,5767.0,1620.0,967.0,3203.0,4412.0

Hesse (2009, 13, 18)

In [487]:
he09 = pd.read_csv(f'{path}/data/elections/ltw/he/2009.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
he13 = pd.read_csv(f'{path}/data/elections/ltw/he/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
he18 = pd.read_csv(f'{path}/data/elections/ltw/he/2018.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [488]:
he09.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,18.01.09,6,Hessen,4375286.0,61,2591872.0,963763.0,614648.0,356040.0,420426.0,139074.0,NaN,97921.0
1,18.01.09,64,"Darmstadt, Regierungsbezirk",2620658.0,"61,9",1576303.0,593959.0,327432.0,240227.0,270740.0,85101.0,NaN,58844.0
2,18.01.09,6411,"Darmstadt, kreisfreie Stadt",98087.0,"62,8",60073.0,17269.0,12730.0,14907.0,9051.0,4322.0,NaN,1794.0
3,18.01.09,6412,"Frankfurt am Main, kreisfreie Stadt",395834.0,"59,4",229893.0,75211.0,45421.0,45134.0,38640.0,18003.0,NaN,7484.0
4,18.01.09,6413,"Offenbach am Main, kreisfreie Stadt",66517.0,"53,6",34483.0,11694.0,7311.0,6350.0,4881.0,2598.0,NaN,1649.0

NRW (2010, 12, 17)

In [489]:
nrw10 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2010.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
nrw12 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2012.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
nrw17 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2017.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [490]:
nrw10.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,09.05.10,5,Nordrhein-Westfalen,13267052.0,"59,3",7760546.0,2681700.0,2675818.0,941162.0,522229.0,435627.0,NaN,504010.0
1,09.05.10,51,"Düsseldorf, Regierungsbezirk",3803015.0,"58,9",2212669.0,742241.0,767674.0,262033.0,157156.0,130781.0,NaN,152784.0
2,09.05.10,5111,"Düsseldorf, kreisfreie Stadt",412910.0,"61,1",249688.0,87499.0,72533.0,37996.0,21710.0,14934.0,NaN,15016.0
3,09.05.10,5112,"Duisburg, kreisfreie Stadt",344154.0,"54,2",184005.0,44331.0,82532.0,17521.0,7242.0,14657.0,NaN,17722.0
4,09.05.10,5113,"Essen, kreisfreie Stadt",433631.0,"58,8",251546.0,72507.0,101932.0,30175.0,13547.0,16265.0,NaN,17120.0

Lower Saxony (2008, 13, 17)

In [491]:
ns08 = pd.read_csv(f'{path}/data/elections/ltw/ns/2008.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
ns13 = pd.read_csv(f'{path}/data/elections/ltw/ns/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
ns17 = pd.read_csv(f'{path}/data/elections/ltw/ns/2017.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [492]:
ns08.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,27.01.08,3,Niedersachsen,6087297.0,"57,1",3425426.0,1456742.0,1036727.0,274221.0,279826.0,243361.0,NaN,134549.0
1,27.01.08,31,"Braunschweig, Stat. Region",1263011.0,"57,2",710602.0,276493.0,241568.0,54767.0,53255.0,56762.0,NaN,27757.0
2,27.01.08,3101,"Braunschweig, kreisfreie Stadt",187773.0,"57,2",106089.0,39106.0,33148.0,11695.0,8580.0,10131.0,NaN,3429.0
3,27.01.08,3102,"Salzgitter, kreisfreie Stadt",78313.0,"54,5",41776.0,15656.0,16405.0,1793.0,2398.0,3688.0,NaN,1836.0
4,27.01.08,3103,"Wolfsburg, kreisfreie Stadt",90631.0,"51,6",45996.0,19834.0,14496.0,2994.0,3078.0,3617.0,NaN,1977.0

Thuringia (2009, 14, 19)

In [493]:
th09 = pd.read_csv(f'{path}/data/elections/ltw/th/2009.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
th14 = pd.read_csv(f'{path}/data/elections/ltw/th/2014.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
th19 = pd.read_csv(f'{path}/data/elections/ltw/th/2019.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [494]:
th09.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,30.08.09,16,Thüringen,1910074.0,"56,2",1054297.0,329302.0,195363.0,64912.0,80600.0,288915.0,NaN,95205.0
1,30.08.09,16051,"Erfurt, kreisfreie Stadt",167444.0,"58,1",95498.0,24134.0,18875.0,10041.0,7226.0,27096.0,NaN,8126.0
2,30.08.09,16052,"Gera, kreisfreie Stadt",85482.0,53,44488.0,12197.0,7002.0,2486.0,3727.0,16096.0,NaN,2980.0
3,30.08.09,16053,"Jena, kreisfreie Stadt",84679.0,"59,1",49407.0,11155.0,11001.0,6818.0,4571.0,12840.0,NaN,3022.0
4,30.08.09,16054,"Suhl, kreisfreie Stadt",34101.0,55,18489.0,4590.0,2949.0,1091.0,1287.0,7108.0,NaN,1464.0

Fix AGS, add year column and state number to dataframes

In [495]:
# Define function to fix the AGS
def ags_fixer(df):
    df = df[df['AGS'] != '']
    df['AGS'] = df['AGS'].astype(int)
    df['AGS'] = df['AGS'].astype(str)
    df['AGS'] = np.where(df['AGS'].str.len() <= 2, df['AGS'] + '0'*6, df['AGS']) # add 6*0 after AGS for states with 1 or 2 digit AGS
    df['AGS'] = np.where(df['AGS'].str.len() < 6, df['AGS'] + '0'*3, df['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
    df['AGS'] = np.where(df['AGS'].str.len() < 8, '0' + df['AGS'], df['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
    return df

In [496]:
dfs = [by08, by13, by18, he09, he13, he18, nrw10, nrw12, nrw17, ns08, ns13, ns17, th09, th14, th19]
years = [2008, 2013, 2018, 2009, 2013, 2018, 2010, 2012, 2017, 2008, 2013, 2017, 2009, 2014, 2019]
states = ['BY', 'BY', 'BY', 'HE', 'HE', 'HE', 'NW', 'NW', 'NW', 'NI', 'NI', 'NI',  'TH', 'TH', 'TH']
for i, (year, df, state) in enumerate(zip(years, dfs, states)):
    try:
        # insert year column and state
        dfs[i].insert(loc=0, column='year', value=year)
        dfs[i].insert(loc=0, column='Land', value=state)
        dfs[i] = dfs[i][dfs[i]['AGS'].str.len() > 3]
        # fix the AGS
        dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
        dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
        dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
    except Exception:
        pass
    # don't have to change the AGS for 2013
    if year == 2013:
        continue
    # read in AGS transition datasets for same year and previous year
    ags_trans_same = pd.read_csv(f'{path}/data/ags_transition.csv', usecols=[f'AGS_{year}', 'AGS_2013'], converters={f'AGS_{year}': str, 'AGS_2013': str})
    ags_trans_same.rename(columns = {f'AGS_{year}':'AGS_new'}, inplace = True)
    ags_trans_prev = pd.read_csv(f'{path}/data/ags_transition.csv', usecols=[f'AGS_{year-1}', 'AGS_2013'], converters={f'AGS_{year-1}': str, 'AGS_2013': str})
    ags_trans_prev.rename(columns = {f'AGS_{year-1}':'AGS_new'}, inplace = True)
    ags_trans = pd.concat([ags_trans_same, ags_trans_prev])
    # merge dfs[i] with ags trans
    dfs[i] = dfs[i].merge(ags_trans, left_on='AGS', right_on=f'AGS_new', how='left', indicator=True)
    print(dfs[i]._merge.value_counts())
    # if merged successfully, replace AGS
    dfs[i]['AGS'] = np.where(dfs[i]['AGS_2013'].notna(), dfs[i]['AGS_2013'], dfs[i]['AGS'])
    dfs[i] = dfs[i].drop(['AGS_2013', f'AGS_new'], axis=1)
    # move AGS to front
    AGS = dfs[i].pop('AGS')
    dfs[i].insert(1, 'AGS', AGS)
# Concatenate dfs
ltw = pd.concat(dfs, sort=False)
ltw.shape

/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)

both          4510
left_only      252
right_only       0
Name: _merge, dtype: int64
both          4510
left_only      253
right_only       0
Name: _merge, dtype: int64
both          860
left_only      23
right_only      0
Name: _merge, dtype: int64

/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)

both          860
left_only      22
right_only      0
Name: _merge, dtype: int64
both          792
left_only      41
right_only      0
Name: _merge, dtype: int64
both          792
left_only      41
right_only      0
Name: _merge, dtype: int64

/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)

both          792
left_only      41
right_only      0
Name: _merge, dtype: int64
both          2122
left_only      108
right_only       0
Name: _merge, dtype: int64
both          2122
left_only      185
right_only       0
Name: _merge, dtype: int64

/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = dfs[i]['AGS'].astype(str)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 6, dfs[i]['AGS'] + '0'*3, dfs[i]['AGS']) # add trailing 000 for kreisfreie Städte (AGS has 4-5 digits before, 7-8 after)
/var/folders/wm/mtrphj0s0msgrmyshf3hgk740000gn/T/ipykernel_95735/1859480891.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs[i]['AGS'] = np.where(dfs[i]['AGS'].str.len() < 8, '0' + dfs[i]['AGS'], dfs[i]['AGS']) # add leading 0 for state ids < 10 (AGS has 7 digits)

both          3432
left_only       59
right_only       0
Name: _merge, dtype: int64
both          3432
left_only      171
right_only       0
Name: _merge, dtype: int64
both          3432
left_only      178
right_only       0
Name: _merge, dtype: int64

(32989, 16)

The merging creates some duplicates --> drop

In [497]:
ltw = ltw.drop_duplicates(keep='first')
ltw.shape

(16527, 16)

Check if AGS was properly calculated

In [498]:
ltw_ags = ltw[ltw['AGS'].str.len() == 8]
ltw_ags.shape
# --> all AGS are 8 digits long
# Still there are some duplicates, e.g. Gießen Stadt and Landkreis --> these won't be matched when merging with treatment data

(16527, 16)

Add County ID

In [499]:
ltw['Kreis'] = ltw['AGS'].str.slice(0,5)
ltw['Kreis'].value_counts()

16061    293
16074    284
16071    260
16075    247
16067    227
        ...
05114      3
05113      3
09162      3
05111      3
05112      3
Name: Kreis, Length: 246, dtype: int64

Add state ID

In [500]:
ltw['state_ID'] = ltw['AGS'].str.slice(0,2)
ltw['state_ID'].value_counts()

09    7056
03    3522
16    3276
06    1362
05    1311
Name: state_ID, dtype: int64

Clean data and sum votes for AfD and Andere

In [501]:
ltw.rename(columns = {'GŸltige Stimmen':'Gültig', 'GrŸne': 'Grüne'}, inplace = True)
andere = ['AfD', 'Sonstige Parteien']
ltw['Andere'] = ltw[andere].sum(axis=1)
ltw.head()

,Land,AGS,year,Datum,Gemeinde,Wahlberechtigte,Wahlbeteiligung,Gültig,Union,SPD,Grüne,FDP,Linke,AfD,Sonstige Parteien,_merge,Kreis,state_ID,Andere
0,BY,09161000,2008,28.09.08,Ingolstadt,87814.0,"49,1",42062.0,16784.0,8303.0,3537.0,3429.0,2265.0,NaN,7745.0,both,09161,09,7745.0
2,BY,09162000,2008,28.09.08,"München, Landeshauptstadt",882602.0,57,496289.0,157505.0,139864.0,71528.0,62369.0,25746.0,NaN,39279.0,both,09162,09,39279.0
4,BY,09163000,2008,28.09.08,Rosenheim,40902.0,"52,1",20831.0,8481.0,3788.0,2686.0,1739.0,938.0,NaN,3200.0,both,09163,09,3200.0
6,BY,09171000,2008,28.09.08,"Altötting, Landkreis",82425.0,"56,4",45350.0,21106.0,8030.0,3542.0,3411.0,1531.0,NaN,7731.0,left_only,09171,09,7731.0
7,BY,09171111,2008,28.09.08,"Altötting, St",9731.0,"52,1",4911.0,2273.0,567.0,335.0,324.0,191.0,NaN,1223.0,both,09171,09,1223.0

Calculate vote shares in percent

In [502]:
parties = ['Union',	'SPD', 'FDP', 'Linke', 'Grüne', 'Andere']
for party in parties:
    ltw.loc[:, party] = (ltw[party] / ltw['Gültig'])*100
ltw.head(10)

,Land,AGS,year,Datum,Gemeinde,Wahlberechtigte,Wahlbeteiligung,Gültig,Union,SPD,Grüne,FDP,Linke,AfD,Sonstige Parteien,_merge,Kreis,state_ID,Andere
0,BY,09161000,2008,28.09.08,Ingolstadt,87814.0,"49,1",42062.0,39.903000,19.739908,8.409015,8.152251,5.384908,NaN,7745.0,both,09161,09,18.413295
2,BY,09162000,2008,28.09.08,"München, Landeshauptstadt",882602.0,57,496289.0,31.736549,28.181967,14.412570,12.567073,5.187703,NaN,39279.0,both,09162,09,7.914542
4,BY,09163000,2008,28.09.08,Rosenheim,40902.0,"52,1",20831.0,40.713360,18.184437,12.894244,8.348135,4.502904,NaN,3200.0,both,09163,09,15.361721
6,BY,09171000,2008,28.09.08,"Altötting, Landkreis",82425.0,"56,4",45350.0,46.540243,17.706725,7.810364,7.521499,3.375965,NaN,7731.0,left_only,09171,09,17.047409
7,BY,09171111,2008,28.09.08,"Altötting, St",9731.0,"52,1",4911.0,46.283853,11.545510,6.821421,6.597434,3.889228,NaN,1223.0,both,09171,09,24.903278
9,BY,09171112,2008,28.09.08,"Burghausen, St",13273.0,"56,6",7326.0,40.281190,26.003276,9.555010,10.455910,3.931204,NaN,718.0,both,09171,09,9.800710
11,BY,09171113,2008,28.09.08,Burgkirchen a.d.Alz,7664.0,"51,3",3846.0,48.465939,19.344774,6.838274,7.124285,2.704108,NaN,597.0,both,09171,09,15.522621
13,BY,09171114,2008,28.09.08,Emmerting,3081.0,"57,5",1722.0,42.508711,16.202091,7.897793,9.407666,2.613240,NaN,369.0,both,09171,09,21.428571
15,BY,09171115,2008,28.09.08,Erlbach,950.0,"63,7",592.0,59.290541,6.418919,5.574324,7.263514,2.027027,NaN,116.0,both,09171,09,19.594595
17,BY,09171116,2008,28.09.08,Feichten a.d.Alz,890.0,"61,1",536.0,52.611940,9.328358,13.432836,7.649254,4.104478,NaN,71.0,both,09171,09,13.246269

Add post-treatment indicator

In [503]:
ltw['post_2014'] = np.where(ltw['year'] >= 2014, 1, 0)
ltw['post_2010'] = np.where(ltw['year'] > 2010, 1, 0)
ltw = ltw.sort_values(['AGS', 'year'])
ltw.head(10)

,Land,AGS,year,Datum,Gemeinde,Wahlberechtigte,Wahlbeteiligung,Gültig,Union,SPD,...,FDP,Linke,AfD,Sonstige Parteien,_merge,Kreis,state_ID,Andere,post_2014,post_2010
0,NI,03101000,2008,27.01.08,"Braunschweig, kreisfreie Stadt",187773.0,"57,2",106089.0,36.861503,31.245464,...,8.087549,9.549529,NaN,3429.0,both,03101,03,3.232192,0,0
2,NI,03101000,2013,20.01.13,"Braunschweig, kreisfreie Stadt",192582.0,"59,9",114222.0,29.666789,33.671272,...,8.250600,4.246117,NaN,6347.0,NaN,03101,03,5.556723,0,1
0,NI,03101000,2017,15.10.17,"Braunschweig, kreisfreie Stadt",190754.0,"63,7",120937.0,26.342641,37.604703,...,7.904115,6.741527,7303.0,4240.0,both,03101,03,9.544639,1,1
2,NI,03102000,2008,27.01.08,"Salzgitter, kreisfreie Stadt",78313.0,"54,5",41776.0,37.476063,39.268958,...,5.740138,8.828035,NaN,1836.0,both,03102,03,4.394868,0,0
3,NI,03102000,2013,20.01.13,"Salzgitter, kreisfreie Stadt",75483.0,"52,5",38983.0,30.880127,44.075623,...,6.053921,4.135136,NaN,2184.0,NaN,03102,03,5.602442,0,1
2,NI,03102000,2017,15.10.17,"Salzgitter, kreisfreie Stadt",73602.0,"56,9",41561.0,24.445995,45.203436,...,5.319891,4.862732,5665.0,944.0,both,03102,03,15.901927,1,1
4,NI,03103000,2008,27.01.08,"Wolfsburg, kreisfreie Stadt",90631.0,"51,6",45996.0,43.121141,31.515784,...,6.691886,7.863727,NaN,1977.0,both,03103,03,4.298200,0,0
4,NI,03103000,2013,20.01.13,"Wolfsburg, kreisfreie Stadt",92716.0,"53,1",48597.0,37.629895,35.812910,...,7.342017,3.210075,NaN,2480.0,NaN,03103,03,5.103196,0,1
4,NI,03103000,2017,15.10.17,"Wolfsburg, kreisfreie Stadt",89468.0,"58,2",51820.0,29.942107,43.211115,...,6.092242,4.525280,4177.0,1251.0,both,03103,03,10.474720,1,1
6,NI,03151000,2008,27.01.08,"Gifhorn, Landkreis",132690.0,57,74634.0,45.717769,30.467347,...,6.957955,6.738216,NaN,2885.0,left_only,03151,03,3.865530,0,0

Subset dataset

In [504]:
ltw = ltw[['AGS', 'Gemeinde', 'Land', 'state_ID', 'Kreis', 'year', 'post_2010', 'post_2014', 'Union', 'SPD', 'Grüne', 'FDP', 'Linke', 'Andere']]
ltw.shape

(16527, 14)

In [505]:
ltw.Land.value_counts(0)

BY    7056
NI    3522
TH    3276
HE    1362
NW    1311
Name: Land, dtype: int64

Inspect balacing of data

In [506]:
dfs = ['BY', 'NI', 'TH', 'HE', 'NW']
for i, df in enumerate(dfs):
    print(df)
    dfs[i] = ltw[ltw['Land'] == df]
    print(dfs[i].year.value_counts())

BY
2018    2354
2008    2351
2013    2351
Name: year, dtype: int64
NI
2017    1212
2008    1155
2013    1155
Name: year, dtype: int64
TH
2019    1235
2009    1021
2014    1020
Name: year, dtype: int64
HE
2018    456
2009    453
2013    453
Name: year, dtype: int64
NW
2010    437
2012    437
2017    437
Name: year, dtype: int64

Merge with treatment dataset

In [507]:
treatment = pd.read_csv(f'{path}/data/treatment.csv', converters = {'AGS': str})
ltw_treat = pd.merge(ltw, treatment, on='AGS', how='left', indicator=True)
ltw_treat['_merge'].value_counts()

both          15329
left_only      1198
right_only        0
Name: _merge, dtype: int64

Clean and export

In [508]:
ltw_treat = ltw_treat[ltw_treat['_merge'] == 'both']
ltw_treat = ltw_treat.drop(columns=['_merge'])
ltw_treat = ltw_treat.set_index(['AGS', 'GEN', 'year'])
ltw_treat.to_csv(f'{path}/data/ltw_treat.csv', encoding = 'utf-8-sig')

Merge in control variables

In [509]:
ltw_treat = ltw_treat.reset_index()
controls = pd.read_csv(f'{path}/data/controls.csv', converters = {'AGS': str})
ltw_controls = pd.merge(ltw_treat, controls, on=['AGS', 'year'], how='left', indicator=True)
ltw_controls['_merge'].value_counts()

both          15148
left_only       181
right_only        0
Name: _merge, dtype: int64

In [510]:
ltw_controls = ltw_controls[ltw_controls['_merge'] == 'both']
ltw_controls = ltw_controls.set_index(['AGS', 'GEN', 'year'])
ltw_controls = ltw_controls.drop(columns=['_merge'])
ltw_controls.shape

(15148, 28)

Export dataset

In [511]:
ltw_controls.to_csv(f'{path}/data/ltw_control.csv', encoding = 'utf-8-sig')
ltw_controls.head()

                                                      Gemeinde Land state_ID  \
AGS      GEN          year
03101000 Braunschweig 2008      Braunschweig, kreisfreie Stadt   NI       03
                      2013      Braunschweig, kreisfreie Stadt   NI       03
                      2017      Braunschweig, kreisfreie Stadt   NI       03
03102000 Salzgitter   2008        Salzgitter, kreisfreie Stadt   NI       03
                      2013        Salzgitter, kreisfreie Stadt   NI       03

                            Kreis  post_2010  post_2014      Union        SPD  \
AGS      GEN          year
03101000 Braunschweig 2008  03101          0          0  36.861503  31.245464
                      2013  03101          1          0  29.666789  33.671272
                      2017  03101          1          1  26.342641  37.604703
03102000 Salzgitter   2008  03102          0          0  37.476063  39.268958
                      2013  03102          1          0  30.880127  44.075623

                                Grüne       FDP  ...  treatment_50  \
AGS      GEN          year                       ...
03101000 Braunschweig 2008  11.023763  8.087549  ...        2005.0
                      2013  18.608499  8.250600  ...        2005.0
                      2017  11.862375  7.904115  ...        2005.0
03102000 Salzgitter   2008   4.291938  5.740138  ...        2005.0
                      2013   9.252751  6.053921  ...        2005.0

                            ever_treated never_treated  pop_density  \
AGS      GEN          year
03101000 Braunschweig 2008   Within 15km           NaN  1280.301848
                      2013   Within 15km           NaN  1286.517146
                      2017   Within 15km           NaN  1287.078360
03102000 Salzgitter   2008   Direct Line           NaN   466.368915
                      2013   Direct Line           NaN   438.549482

                           unemployed   foreign   catholic  avg_age  female  \
AGS      GEN          year
03101000 Braunschweig 2008   4.627010  7.309400  14.008172    43.07   50.85
                      2013   3.762130  7.309400  14.008172    43.16   50.91
                      2017   3.240828       NaN        NaN    43.37   50.52
03102000 Salzgitter   2008   4.766191  8.932706  17.653066    43.99   51.09
                      2013   4.765930  8.932706  17.653066    45.13   51.23

                            income_pc
AGS      GEN          year
03101000 Braunschweig 2008  10.340290
                      2013  10.503475
                      2017        NaN
03102000 Salzgitter   2008  10.172468
                      2013  10.290011

[5 rows x 28 columns]