First, import needed modules

In [24]:
import numpy as np
import pandas as pd
import os

Initalize variables

In [25]:
path = os.getcwd()
print(path)

/Users/jan/Dropbox/UP_EPQM/2222/MA/powerlinemonsters

Import datasets

In [26]:
import chardet
with open(f'{path}/data/elections/ltw/by/2018.csv', 'rb') as file:
    print(chardet.detect(file.read()))

{'encoding': 'Windows-1252', 'confidence': 0.6976500787401575, 'language': ''}

Bavaria (2008, 13, 18)

In [27]:
by08 = pd.read_csv(f'{path}/data/elections/ltw/by/2008.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
by13 = pd.read_csv(f'{path}/data/elections/ltw/by/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
by18 = pd.read_csv(f'{path}/data/elections/ltw/by/2018.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [28]:
by18.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,14.10.18,9,Bayern,9479428.0,"72,3",6782374.0,2523041.0,654539.0,1196178.0,345250.0,218944.0,694311.0,1150112.0
1,14.10.18,91,"Oberbayern, Regierungsbezirk",3203709.0,"74,6",2367136.0,798011.0,221710.0,527462.0,151403.0,74839.0,202708.0,391004.0
2,14.10.18,9161,Ingolstadt,90643.0,64,57337.0,20784.0,5217.0,9517.0,3972.0,2894.0,7383.0,7572.0
3,14.10.18,9162,"München, Landeshauptstadt",910459.0,"72,7",656649.0,162579.0,84340.0,204303.0,57488.0,30752.0,42441.0,74748.0
4,14.10.18,9163,Rosenheim,41029.0,"68,2",27618.0,9396.0,2254.0,5767.0,1620.0,967.0,3203.0,4412.0

Hesse (2009, 13, 18)

In [29]:
he09 = pd.read_csv(f'{path}/data/elections/ltw/he/2009.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
he13 = pd.read_csv(f'{path}/data/elections/ltw/he/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
he18 = pd.read_csv(f'{path}/data/elections/ltw/he/2018.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [30]:
he09.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,18.01.09,6,Hessen,4375286.0,61,2591872.0,963763.0,614648.0,356040.0,420426.0,139074.0,NaN,97921.0
1,18.01.09,64,"Darmstadt, Regierungsbezirk",2620658.0,"61,9",1576303.0,593959.0,327432.0,240227.0,270740.0,85101.0,NaN,58844.0
2,18.01.09,6411,"Darmstadt, kreisfreie Stadt",98087.0,"62,8",60073.0,17269.0,12730.0,14907.0,9051.0,4322.0,NaN,1794.0
3,18.01.09,6412,"Frankfurt am Main, kreisfreie Stadt",395834.0,"59,4",229893.0,75211.0,45421.0,45134.0,38640.0,18003.0,NaN,7484.0
4,18.01.09,6413,"Offenbach am Main, kreisfreie Stadt",66517.0,"53,6",34483.0,11694.0,7311.0,6350.0,4881.0,2598.0,NaN,1649.0

NRW (2010, 12, 17)

In [31]:
nrw10 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2010.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
nrw12 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2012.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
nrw17 = pd.read_csv(f'{path}/data/elections/ltw/nrw/2017.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [32]:
nrw10.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,09.05.10,5,Nordrhein-Westfalen,13267052.0,"59,3",7760546.0,2681700.0,2675818.0,941162.0,522229.0,435627.0,NaN,504010.0
1,09.05.10,51,"Düsseldorf, Regierungsbezirk",3803015.0,"58,9",2212669.0,742241.0,767674.0,262033.0,157156.0,130781.0,NaN,152784.0
2,09.05.10,5111,"Düsseldorf, kreisfreie Stadt",412910.0,"61,1",249688.0,87499.0,72533.0,37996.0,21710.0,14934.0,NaN,15016.0
3,09.05.10,5112,"Duisburg, kreisfreie Stadt",344154.0,"54,2",184005.0,44331.0,82532.0,17521.0,7242.0,14657.0,NaN,17722.0
4,09.05.10,5113,"Essen, kreisfreie Stadt",433631.0,"58,8",251546.0,72507.0,101932.0,30175.0,13547.0,16265.0,NaN,17120.0

Lower Saxony (2008, 13, 17)

In [33]:
ns08 = pd.read_csv(f'{path}/data/elections/ltw/ns/2008.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
ns13 = pd.read_csv(f'{path}/data/elections/ltw/ns/2013.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
ns17 = pd.read_csv(f'{path}/data/elections/ltw/ns/2017.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [34]:
ns08.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,27.01.08,3,Niedersachsen,6087297.0,"57,1",3425426.0,1456742.0,1036727.0,274221.0,279826.0,243361.0,NaN,134549.0
1,27.01.08,31,"Braunschweig, Stat. Region",1263011.0,"57,2",710602.0,276493.0,241568.0,54767.0,53255.0,56762.0,NaN,27757.0
2,27.01.08,3101,"Braunschweig, kreisfreie Stadt",187773.0,"57,2",106089.0,39106.0,33148.0,11695.0,8580.0,10131.0,NaN,3429.0
3,27.01.08,3102,"Salzgitter, kreisfreie Stadt",78313.0,"54,5",41776.0,15656.0,16405.0,1793.0,2398.0,3688.0,NaN,1836.0
4,27.01.08,3103,"Wolfsburg, kreisfreie Stadt",90631.0,"51,6",45996.0,19834.0,14496.0,2994.0,3078.0,3617.0,NaN,1977.0

Thuringia (2009, 14, 19)

In [35]:
th09 = pd.read_csv(f'{path}/data/elections/ltw/th/2009.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
th14 = pd.read_csv(f'{path}/data/elections/ltw/th/2014.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')
th19 = pd.read_csv(f'{path}/data/elections/ltw/th/2019.csv', encoding = 'Windows-1252', sep=';', converters = {'AGS': str}, na_values='-')

In [36]:
th09.head()

,Datum,AGS,Gemeinde,Wahlberechtigte,Wahlbeteiligung,GŸltige Stimmen,Union,SPD,GrŸne,FDP,Linke,AfD,Sonstige Parteien
0,30.08.09,16,Thüringen,1910074.0,"56,2",1054297.0,329302.0,195363.0,64912.0,80600.0,288915.0,NaN,95205.0
1,30.08.09,16051,"Erfurt, kreisfreie Stadt",167444.0,"58,1",95498.0,24134.0,18875.0,10041.0,7226.0,27096.0,NaN,8126.0
2,30.08.09,16052,"Gera, kreisfreie Stadt",85482.0,53,44488.0,12197.0,7002.0,2486.0,3727.0,16096.0,NaN,2980.0
3,30.08.09,16053,"Jena, kreisfreie Stadt",84679.0,"59,1",49407.0,11155.0,11001.0,6818.0,4571.0,12840.0,NaN,3022.0
4,30.08.09,16054,"Suhl, kreisfreie Stadt",34101.0,55,18489.0,4590.0,2949.0,1091.0,1287.0,7108.0,NaN,1464.0

Add year column and state number to dataframes

In [37]:
dfs = [by08, by13, by18, he09, he13, he18, nrw10, nrw12, nrw17, ns08, ns13, ns17, th09, th14, th19]
years = [2008, 2013, 2018, 2009, 2013, 2018, 2010, 2012, 2017, 2008, 2013, 2017, 2009, 2014, 2019]
states = ['09', '09', '09', '06', '06', '06', '05', '05', '05', '03', '03', '03',  '16', '16', '16']
for df, year, state in zip(dfs, years, states):
    df.insert(loc=0, column='year', value=year)
    df.insert(loc=0, column='Land', value=state)